### ISSUE TITLE
Please list the content openly without logins

### ISSUE THREAD

**Issue by PrathamH** [tks18/gindex-v4#114]
I think this is too much to not showcase what the user is going to get.
The content should be listed and showcased but not download able until the user registers. This way it's better. Because the visitor will see the home page and go away without any interest.
This is big advantage of other google drive indexes that they show the user all files.
By the way, awesome look you have given.

**Comment by tks18** [comment]
Bro the Main Purpose of User based Access System is for Restricting.
Also Like What You are Saying We can't do because we don't have a database of content that is Stored. Then How we can Restrict. Either Fully or No Restriction.
if you need a Gindex without backend.
Here you Go - https://github.com/tks18/gindex-v4-no-backend

**Comment by PrathamH** [comment]
Thanks tried the no-backend one. That's allright.
