### ISSUE TITLE
Theme change not working

### ISSUE THREAD

**Issue by stephnlynn** [tks18/gindex-v4#259]
I've write the theme name on cloudflare workers by reading the wiki and only the initial theme show nothing change.

**Comment by tks18** [comment]
I have Removed the Theme Functionality in the Latest version, You can use
the Version 8.2.9 for the theme to be working

With Regards,
Sudharshan TK
FRP

Disclaimer:
The information contained in this email and any attachments are intended
for the exclusive use of the addressee(s) and may contain proprietary,
confidential or privileged information. If you are not the intended
recipient, you should not disseminate, distribute or copy this email.
Please notify the sender immediately and destroy all copies of this message
and any attachments.

WARNING: Computer viruses can be transmitted via email. The recipient
should check this email and any attachments for the presence of viruses. I
accept no liability for any damage caused by any virus transmitted by this
email.

**Comment by tks18** [comment]
Also Use the Worker file used in that Version

here - https://github.com/tks18/gindex-v4/blob/frontend-8.2.9/worker/index.js

**Comment by stephnlynn** [comment]
Thank you.
